# NUMPY RIVISON

In [1]:
# print numpy array
import numpy as np 
n=np.array([1,2,3,4,5,6,7]) 
print(n) 
print(type(n))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
# print numpy array using slicing
import numpy as np 
n=np.array([1,2,3,4,5,6,7]) 
print(n[3:7]) 
print(type(n))

[4 5 6 7]
<class 'numpy.ndarray'>


# check dimension and type

In [8]:
#check dimension and type
n=np.array([[[1,2,3],[5,6,7]]])
print(n)
print(n.ndim)
print(type(n))

[[[1 2 3]
  [5 6 7]]]
3
<class 'numpy.ndarray'>


In [6]:
#check dimension and type
n=np.array([[[1,2,3],[5,6,7],[11,22,33]]])
print(n)
print(n.ndim)
print(type(n))

[[[ 1  2  3]
  [ 5  6  7]
  [11 22 33]]]
3
<class 'numpy.ndarray'>


In [7]:
#check dimension and type
n=np.array([[[[[[1,2]]]]]])
print(n)
print(n.ndim)
print(type(n))

[[[[[[1 2]]]]]]
6
<class 'numpy.ndarray'>


In [4]:
# print numpy using list
l1=[11,22,33,44,55,66,77,88]
n=np.array(l1)
print(n)

[11 22 33 44 55 66 77 88]


In [5]:
# print numpy array using range
n=np.array(range(1,10))
print(n)

[1 2 3 4 5 6 7 8 9]


In [16]:
# print numpy array using range
n=np.array(range(1,10))
print(n[3:8])

[4 5 6 7 8]


In [44]:
# print numpy array using arange
n=np.arange(1,10)
print(n)

[1 2 3 4 5 6 7 8 9]


In [9]:
# print numpy array using for loop
import numpy as np

l1 = [11, 22, 33, 44, 55, 66, 77, 88]
array = np.array(l1)

for i in range(len(array)):
    print(array[i],end=" ")


5 10 15 20 25 30 35 40 45 

In [8]:
# print zeros array of numpy
n1=np.zeros(3)
print(n1)
print(n1.ndim)
# print zeros array of numpy by row and columns
n=np.zeros((2,4))
print(n)
print(n.ndim)
# Two rows
# Four column

[0. 0. 0.]
1
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [9]:
# print ones array of numpy
n=np.ones(10)
print(n)
# print ones array of numpy by row and columns
n=np.ones((3,4))
print(n)
print(type(n))
# Three rows
# Four column

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [11]:
# print ones array of numpy
n=np.ones(10)
print(n)
# print ones array of numpy by row and columns
n=np.ones((3,4))
print(n)
print(type(n))
# Three rows
# Four column

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [13]:
n=np.eye(5)
print(n)
# Identity matrix
# Ones of diagonal with Zeros

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# Check Datatype of array and how to change datatype of array
n=np.array([11,22,33,55])
print("Data Type : ",n.dtype)
print(n)
print()
n1=np.array([11,22,33,55],dtype='f')
print("Data Type : ",n1.dtype)
print(n1)
print()
m=np.array([3.5,6.7])
print("Data Type : ",m.dtype)
print(m)
print()
m1=np.array([3.5,6.7],dtype='i')
print("Data Type : ",m1.dtype)
print(m1)
print()
p=np.array(['bj','dj','mj'])
print("Data Type : ",p.dtype)
print(p)
print()
q=np.array([11,2.5,"bj"])
print("Data Type : ",q.dtype)
print(q)

Data Type :  int32
[11 22 33 55]

Data Type :  float32
[11. 22. 33. 55.]

Data Type :  float64
[3.5 6.7]

Data Type :  int32
[3 6]

Data Type :  <U2
['bj' 'dj' 'mj']

Data Type :  <U32
['11' '2.5' 'bj']


In [45]:
# Data type conversion
n=np.array([1,2,3,4,5,6],dtype="f")
print("Data Type :",n.dtype)
print(n)

Data Type : float32
[1. 2. 3. 4. 5. 6.]


#  Shape And Reshape

In [20]:
n=np.array([1,2,3])
print(n)
print(n.shape)

[1 2 3]
(3,)


In [51]:
#Shape
n=np.array([[1,2,3],[3,4,6]])
print(n)
print("number of rows and columns: ",n.shape)
# The output  (2,3) represent TWO rows and THREE column

[[1 2 3]
 [3 4 6]]
number of rows and columns:  (2, 3)


In [21]:
#Shape
n=np.array([[1,2,3,4],[3,4,6,7]])
print(n)
print("number of rows and columns: ",n.shape)
# The output  (2,3) represent TWO rows and THREE column

[[1 2 3 4]
 [3 4 6 7]]
number of rows and columns:  (2, 4)


In [26]:
n=np.array([1,2,3,4,5,6])
print(n)
print(n.reshape(3,2))
#Convert array of 6 elements from 1 to 6 TO 3 rows and 2 columns
# reshape(3,2) represent three rows and two columns

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [97]:
n=np.arange(1,13)
print(n.reshape(4,3))
#Convert array of 12 elements from 1 to 12 TO 4 rows and 3 columns
# reshape(4,3) represent three rows and two columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [68]:
n=np.array(range(1,10))
print(n)
print()
print("number of rows and columns: " , n.reshape(3,3))

[1 2 3 4 5 6 7 8 9]

number of rows and columns:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
n=np.array(range(20))
print(n)
print()
print("number of rows=4 and columns=5")
print(n.reshape(4,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

number of rows=4 and columns=5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [33]:
n=np.array(range(20,44,2))
print(n)
print()

print(n.reshape(4,3))

[20 22 24 26 28 30 32 34 36 38 40 42]

[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]]


# Arithmatic Operation

In [65]:
n1=np.array([1,2,3])
print("ADDITION: ",n1+3)
print("SUSTRACTION: ",n1-3)
print("MULTIPLICATION: ",n1*3)
print("DIVISION: ",n1/3)
print("POWER: ",n1**3)
print("MOD: ",n1%3)


ADDITION:  [4 5 6]
SUSTRACTION:  [-2 -1  0]
MULTIPLICATION:  [3 6 9]
DIVISION:  [0.33333333 0.66666667 1.        ]
POWER:  [ 1  8 27]
MOD:  [1 2 0]


In [73]:
n1=np.array([1,2,3])
n2=np.array([8,3,6])
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)
print(n1**n2)
print(n1%n2)

[9 5 9]
[-7 -1 -3]
[ 8  6 18]
[0.125      0.66666667 0.5       ]
[  1   8 729]
[1 2 3]


In [71]:
n1=np.array([1,2,3])
print(np.add(n1,5))
print(np.subtract(n1,5))
print(np.multiply(n1,5))
print(np.divide(n1,5))
print(np.power(n1,5))
print(np.mod(n1,5))


[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]
[  1  32 243]
[1 2 3]


In [72]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
print(np.add(n1,n2))
print(np.subtract(n1,n2))
print(np.multiply(n1,n2))
print(np.divide(n1,n2))
print(np.power(n1,n2))
print(np.mod(n1,n2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]


In [86]:
n=np.array(range(7))
print(np.add(n,4))
print(np.subtract(n,4))
print(np.multiply(n,4))
print(np.divide(n,4))
print(np.power(n,4))
print(np.mod(n,4))

[ 4  5  6  7  8  9 10]
[-4 -3 -2 -1  0  1  2]
[ 0  4  8 12 16 20 24]
[0.   0.25 0.5  0.75 1.   1.25 1.5 ]
[   0    1   16   81  256  625 1296]
[0 1 2 3 0 1 2]


In [88]:
n=np.arange(3)
print(np.add(n,4))
print(np.subtract(n,4))
print(np.multiply(n,4))
print(np.divide(n,4))
print(np.power(n,4))
print(np.mod(n,4))

[4 5 6]
[-4 -3 -2]
[0 4 8]
[0.   0.25 0.5 ]
[ 0  1 16]
[0 1 2]


In [100]:
n1=np.array(range(1,5))
n2=np.array(range(2,10,2))
print(n2)
print(np.add(n1,n2))

[2 4 6 8]
[ 3  6  9 12]


In [103]:
n1=np.arange(1,5)
n2=np.arange(2,10,2)
print(n2)
print(np.add(n1,n2))

[2 4 6 8]
[ 3  6  9 12]


In [63]:
# Arithmatic Function
n1=np.array([3,2,7,11,9,10])
print(np.min(n1))
print(np.max(n1))
print(np.sqrt(n1))
print(np.sin(n1))
print(np.cos(n1))
print(np.min(n1),np.argmin(n1)) # min value and their location
print(np.max(n1),np.argmax(n1))  # max value and their location
n2=np.array([1,2,3,4,5])
print(np.cumsum(n2))
# cumsum function means o/p is 1,1+2=3,3+3=6,6+4=10,10+5=15 

2
11
[1.73205081 1.41421356 2.64575131 3.31662479 3.         3.16227766]
[ 0.14112001  0.90929743  0.6569866  -0.99999021  0.41211849 -0.54402111]
[-0.9899925  -0.41614684  0.75390225  0.0044257  -0.91113026 -0.83907153]
2 1
11 3
[ 1  3  6 10 15]


In [64]:
n1=np.array([[2,1,3],[9,5,6]])
print(n1)
print(np.min(n1,axis=1))
print(np.min(n1,axis=0))
print()
print(np.max(n1,axis=1))
print(np.max(n1,axis=0))
print(n1[0,0]) # 0 indicate zeroth row and 0 indicate zeroth column 
print(n1[0,1]) # 0 indicate zeroth row and 1 indicate zeroth column
print(n1[0,2]) # 0 indicate zeroth row and 2 indicate zeroth column
print(n1[1,0]) # 1 indicate zeroth row and 0 indicate zeroth column
print(n1[1,1]) # 1 indicate zeroth row and 1 indicate zeroth column
print(n1[1,2]) # 1 indicate zeroth row and 2 indicate zeroth column
# axis=1 means ROWS
# axis=0 means COLUMNS

[[2 1 3]
 [9 5 6]]
[1 5]
[2 1 3]

[3 9]
[9 5 6]
2
1
3
9
5
6


# linsspace array in numpy

In [21]:
# linsspace array
# Create array with values that are spaced linearly in a specified interval
n=np.linspace(1,10,5)
print(n)
# Explain of linspace(1,10,5)
# 1 means Start of array
# 10 means last values 1 to 10
# 5 means 5 time print 5 number of space linearly
# The difference is from 1 to 3.25 is "2.25" and so all same difference 3.25 to 5.5 is also 2.25
# (1,10,5) means (start,end,how many times)

[ 1.    3.25  5.5   7.75 10.  ]


In [27]:
n=np.linspace(1,10,10)
print(n)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [47]:
n=np.linspace(1,20,5)
print(n)

[ 1.    5.75 10.5  15.25 20.  ]


In [29]:
n=np.linspace(1,20,3)
print(n)

[ 1.  10.5 20. ]


In [30]:
n=np.linspace(5,25,15)
print(n)

[ 5.          6.42857143  7.85714286  9.28571429 10.71428571 12.14285714
 13.57142857 15.         16.42857143 17.85714286 19.28571429 20.71428571
 22.14285714 23.57142857 25.        ]


# Random numbers array in numpy 

In [144]:
# 1> random() Create a row*column like 2*3 and  array of random values
n=np.random.random((2, 3))
n1=np.random.random((4, 3))
print( n)
print()
print(n1)


[[0.40522978 0.74508944 0.20444844]
 [0.51875733 0.48661222 0.29740958]]

[[0.51226283 0.59734257 0.85854688]
 [0.28342587 0.59783304 0.95362629]
 [0.80854711 0.82338347 0.50476149]
 [0.62865139 0.64539779 0.11824951]]


In [3]:
# 2> rand() function to generate values between 0 to 1
n1=np.random.rand(4)
print(n1)

[0.34059173 0.72734913 0.49317601 0.18279084]


In [4]:
n1=np.random.rand(1)
print(n1)

[0.38340694]


In [5]:
n1=np.random.rand(6)
print(n1)

[0.86980759 0.77975704 0.58856595 0.46075877 0.82714024 0.61954281]


In [15]:
# 3> randn() this function to generate values close to ZERO value may be positive or negative
n1=np.random.randn(3)
print(n1)

[-1.02771811  0.9372577   1.03994518]


In [94]:
# 4> randf() this function to generate values [0.0 , 1.0]
n1=np.random.ranf(5)
print(n1)

[0.41647629 0.1792238  0.01849819 0.50497742 0.25856047]


In [105]:
n1=np.random.ranf(3)
print(n1)

[0.25537269 0.70036906 0.23911562]


In [137]:
# 5> this function use to generate a value in the range
n1=np.random.randint(0,10,6)
print(n1)

[2 8 8 2 3 2]


In [161]:
n1=np.random.randint(0,5,3)
print(n1)

[2 3 1]


In [167]:
n1=np.random.randint(11,18,4)
print(n1)

[16 15 16 13]


# Generate OPT using randint function in numpy

In [20]:
otp=np.random.randint(0,10,6)
otp="".join(map(str,np.random.randint(0,10,6)))
print(otp)

319530


# Join & Split

In [26]:
# Join
#join function is used to concate two array in a single array
n=np.array([1,2,3,4,5,6,7,8])
n1=np.array([11,22,33,44,55,66,77,88])
n3=np.concatenate((n,n1),axis=0)
n33=np.concatenate((n1,n))
print(n3)
print(n33)
print()

n4=np.array([[1,2,3],[11,22,33]])
n5=np.array([[9,8,7],[99,88,77]])
n6=np.concatenate((n4,n5),axis=1) #axis=1 denote row
print(n6)
print(n4.shape)
print(n4.ndim)
print()

n7=np.array([[1,2,3],[11,22,33]])
n8=np.array([[9,8,7],[99,88,77]])
n9=np.concatenate((n4,n5),axis=0)   #axis=0 denote column
print(n9)


[ 1  2  3  4  5  6  7  8 11 22 33 44 55 66 77 88]
[11 22 33 44 55 66 77 88  1  2  3  4  5  6  7  8]

[[ 1  2  3  9  8  7]
 [11 22 33 99 88 77]]
(2, 3)
2

[[ 1  2  3]
 [11 22 33]
 [ 9  8  7]
 [99 88 77]]


In [40]:
# some additional future of join
#1 stack axis wise
#2 hstack row
#3 vstack column
#4 dstack height

n1=np.arange(1,10,2)
n2=np.arange(11,20,2)
x1=np.stack((n1,n2))
x2=np.hstack((n1,n2)) # same work convert single array 
x=np.concatenate((n1,n2))# same work convert single array
x3=np.vstack((n1,n2))
x4=np.dstack((n1,n2))
print(x1)
print()
print(x2)
print(x)
print()
print(x3)
print()
print(x4)
print()

[[ 1  3  5  7  9]
 [11 13 15 17 19]]

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]

[[ 1  3  5  7  9]
 [11 13 15 17 19]]

[[[ 1 11]
  [ 3 13]
  [ 5 15]
  [ 7 17]
  [ 9 19]]]



In [56]:
#Split
#split function used to break the one array into multiple array
n1=np.array(range(1,10))
n2=np.array(range(1,7))
x1=np.array_split(n1,3)
x2=np.array_split(n2,2)
x3=np.array_split(n2,3)
x4=np.array_split(n2,6)
x5=np.array_split(n2,7)
x6=np.array_split(n2,1)
print(x1)
print(x2)
print(x3)
print(x4)
print(x5)
print(x6)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]
[array([1, 2, 3, 4, 5, 6])]


# Search,sort,search sorted,filter function in numpy

In [70]:
#1 Search -: search an array for a certain value and return the index that get a match
n=np.array([1,2,3,4,11,2,44,11,5,22,1,4,3,12,133,11,3,1135,6,32,3,4,3])
n1=np.array([1,2,3,4,11,2,44,11,5,22,1,0,3,12,133,0,3,1135,6,32,3,4,3])
print(np.where(n==3))
print()
x=np.where(n>100)  # return the index of n values that are greater than 100 
print(x)
print()
x1=np.where(n1%2==0)  # return the index
print(x1)
print(len(n))
print()
print()

n3=np.array([1,2,3,4,0,44,3,0,12])
x4=np.argwhere(n3) # return non zero index
print(x4)




(array([ 2, 12, 16, 20, 22], dtype=int64),)

(array([14, 17], dtype=int64),)

(array([ 1,  3,  5,  6,  9, 11, 13, 15, 18, 19, 21], dtype=int64),)
23


[[0]
 [1]
 [2]
 [3]
 [5]
 [6]
 [8]]


In [74]:
#2 Search sorted
# search sorted :- This function is useful for searching within continue with below line
#  a sorted array and finding the position where new elements should be inserted to maintain the sorted order.

n=np.array([11,22,33,44,55,66,77,88,99])
n1=np.searchsorted(n,50)
print(n1)
n2=np.arange(11,50,5)
print(n2)
x1=np.searchsorted(n2,42)
print(x1)

4
[11 16 21 26 31 36 41 46]
7


In [106]:
#Sort -: sort the given array in the linear order
n=np.arange(100,0,-1)
print(n)
print()
n1=np.sort(n)
print(n1)
print()
n2=np.array([11,22,33,5,2,66,3,12,4])
print(np.sort(n2))
print()
n5=np.arange(10,1,-1)
n6=n5.reshape(3,3)
print(n6)
print()
print(np.sort(n6))
print()
nn1=np.array([[4,2,3],[1,12,5],[22,52,6]])
print(np.sort(nn1))

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

[ 2  3  4  5 11 12 22 33 66]

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]

[[ 8  9 10]
 [ 5  6  7]
 [ 2  3  4]]

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [141]:
#Filter:- The filter function is not a direct function in NumPy using some numpy function according to condition filter in used
n1=np.arange(10,1000,50)
print(n1)
print()
filter_aar1=n1[n1>500]
print("Filtered values = ",filter_aar)
print()
filter_arr2=n1[(n1>500) & (n1<800)]
print(filter_arr2)


[ 10  60 110 160 210 260 310 360 410 460 510 560 610 660 710 760 810 860
 910 960]

Filtered values =  [510 560 610 660 710 760 810 860 910 960]

[510 560 610 660 710 760]


In [132]:
l=[11,22,33,44]
print(l)
print("Note the difference between both output. BY USING * AND NOT USING *")
print(*l)
# print(*l) this is correct show output without error
# print(l*) this is incorrect show error

[11, 22, 33, 44]
Note the difference between both output. BY USING * AND NOT USING *
11 22 33 44


# shuffle,unique,resize,flatten function of numpy

In [28]:
#1 shuffle
# this function is used to print random values in the existing arraay
n=np.array([1,2,3,4,5,6,7,8])
print("Original Array:",n)
np.random.shuffle(n)
print("By using shuffle function print random values: ",n)


Original Array: [1 2 3 4 5 6 7 8]
By using shuffle function print random values:  [6 4 2 1 5 7 8 3]


In [31]:
#1 shuffle
# this function is used to print random values in the existing arraay
n=np.array([1,2,3,4,5,6,7,8])
print("Original Array:",n)
np.random.shuffle(n)
print("By using shuffle function print random values: ",n)



Original Array: [1 2 3 4 5 6 7 8]
By using shuffle function print random values:  [7 1 3 5 4 6 8 2]


In [35]:
#2 unique
# this function use for print just unique values not repeated
n1=np.array([1,2,3,44,5,2,1,5,3,7,2,3,44,5])
print(len(n1))
x=np.unique(n1)
print(x)
print(len(x))


14
[ 1  2  3  5  7 44]
6


In [45]:
#3 resize
# this function is used to print the array in resizeable like number of rows and number of column
n1=np.arange(1,10)
x=np.resize(n1,(3,3))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
n1=np.array([1,2,3,4,5,6,7,8,9])
x=np.resize(n1,(2,3))
print(x)
# focus on the output is show we provide 2,3 means 2 rows and 3 columns in this case output is printed 
# the conclusion is does not matter the total length of array

[[1 2 3]
 [4 5 6]]


In [49]:
n1=np.array([1,2,3,4,5,6,7,8,9])
x=np.resize(n1,(5,3))
print(x)
# focus on the output is show we provide 2,3 means 2 rows and 3 columns in this case output is printed 
# the conclusion is does not matter the total length of array

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]]


In [57]:
#4 flatten 
# Returns single dimension  array, flattening any multidimensional array into a single-dimensional array
n1=np.array([[1,2,3],[4,5,6]])
print(n1)
print()
x=n1.flatten()
print(x)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [58]:
n1=np.arange(1,10)
n=np.resize(n1,(3,3))
print(n)
print()
x=n.flatten()
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


# Insert , delete,function in numpy

In [62]:
#1 insert this function is used to insert the specific values , row, of the specific location
n1=np.array([11,22,33,44,55,66])
print("Original arraay:",n1)
x=np.insert(n1,3,111) # 3 is the location and 111 is the value
print(x)

Original arraay: [11 22 33 44 55 66]
[ 11  22  33 111  44  55  66]


In [65]:
n2=np.array([11,22,33,44,55,66])
x=np.insert(n2,(1,5),222)
print(x)

[ 11 222  22  33  44  55 222  66]


In [68]:
n2=np.array([11,22,33,44,55,66])
x=np.insert(n2,(1,5,0),222)
print(x)

[222  11 222  22  33  44  55 222  66]


In [74]:
n2=np.array([11,22,33,44,55,66])
print("length:",len(n2))
x=np.insert(n2,(1,5,0,2,6),222)
print(x)
print(len(x))

length: 6
[222  11 222  22 222  33  44  55 222  66 222]
11


In [87]:
n=np.arange(1,10)
print(n)
print()
n1=n.reshape(3,3)
print(n1)
print()
n2=np.insert(n1,2,[11,22,33],axis=0)
n3=np.insert(n2,3,[111,222,333],axis=0)
print(n2)
print()
print(n3)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [ 7  8  9]]

[[  1   2   3]
 [  4   5   6]
 [ 11  22  33]
 [111 222 333]
 [  7   8   9]]


In [100]:
#2 delete is used to delete the element of the array
n1=np.array(range(1,13))
print("Original array:",n1)
print()
#print(n1.reshape(4,3))
x=np.delete(n1,2)
print("After using delete function:",x)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After using delete function: [ 1  2  4  5  6  7  8  9 10 11 12]


In [104]:
#2 delete is used to delete the element of the array
n1=np.array(range(1,13))
print("Original array:",n1)
print()
#print(n1.reshape(4,3))
x=np.delete(n1,[1,3])
print("After using delete function:",x)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After using delete function: [ 1  3  5  6  7  8  9 10 11 12]


In [107]:
#2 delete is used to delete the element of the array
n1=np.array(range(1,13))
print("Original array:",n1)
print()
#print(n1.reshape(4,3))
x=np.delete(n1,[1,3,10])
print("After using delete function:",x)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After using delete function: [ 1  3  5  6  7  8  9 10 12]


In [110]:
#2 delete is used to delete the element of the array
n1=np.array(range(1,13))
print("Original array:",n1)
print()
n3=n1.reshape(4,3)
print(n3)
x=np.delete(n3,2,axis=0)
print("After using delete function:",x)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After using delete function: [[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


# Matrix in numpy array

In [134]:
# Matrix in numpy it is create by 'matrix' keyword
n1=np.matrix([[1,2,3],[4,5,6]])
print(n1)
print()
print(type(n1))
print()
print("Shape of matrix no. of row and column:",n1.shape)
print()
print("Dimension:",n1.ndim)

[[1 2 3]
 [4 5 6]]

<class 'numpy.matrix'>

Shape of matrix no. of row and column: (2, 3)

Dimension: 2


In [135]:
n1=np.matrix(range(1,13))
n=n1.reshape(4,3)
print(n)
print()
print(type(n))
print(n.shape)
print(n.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

<class 'numpy.matrix'>
(4, 3)
2


In [139]:
n1=np.matrix(range(1,13))
print(n1)
print()
print(type(n1))
print(n1.shape)
print(n1.ndim)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

<class 'numpy.matrix'>
(1, 12)
2


In [140]:
n = np.matrix(np.arange(1,7))
print(n)
print(type(n))


[[1 2 3 4 5 6]]
<class 'numpy.matrix'>


In [162]:
n1=np.matrix([[1,2],[3,4]])
print(n1)
print()
n2=np.matrix([[4,1],[2,3]])
print(n2)
print()
n=n1*n2
print(n)
print()
n3=(n1.dot(n2))

print(n3)


[[1 2]
 [3 4]]

[[4 1]
 [2 3]]

[[ 8  7]
 [20 15]]

[[ 8  7]
 [20 15]]


In [165]:
n1=np.matrix(np.arange(1,10))
n2=np.matrix(np.arange(1,10))
n3=n1.reshape(3,3)
print(n3)
print()
n4=n2.reshape(3,3)
print(n4)
print()
print(n3*n4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Matrix function in numpy arrays 

# 1 Transpose
# 2 Swapaxes
# 3 Inverse
# 4 Power
# 5 Determinate

In [169]:
#1 Transpose
n=np.matrix([[1,2,3],[5,6,7]])
print(n)
print()
n1=np.transpose(n)
print(n1)

[[1 2 3]
 [5 6 7]]

[[1 5]
 [2 6]
 [3 7]]


In [174]:
n=np.matrix(np.arange(1,10))
n1=n.reshape(3,3)
print(n1)
print()
print(np.transpose(n1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [178]:
#2  Swapaxes
n=np.matrix(range(1,7))
n1=n.reshape(2,3)
print(n1)
n2=np.swapaxes(n1,0,1)
print(n2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [179]:
#2  Swapaxes
n=np.matrix(range(1,7))
n1=n.reshape(2,3)
print(n1)
n2=np.swapaxes(n1,1,0)
print(n2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [201]:
#3 Inverse
n1=np.matrix(range(1,5))
n2=n1.reshape(2,2)
print(n2)
print()
n3=np.linalg.inv(n2)
print("Inverse matrix:\n",n3)

[[1 2]
 [3 4]]

Inverse matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [188]:
#4 Power
n=np.matrix([[1,2],[1,2]])
print(n)
print()
n1=np.linalg.matrix_power(n,2)
print(n1)


[[1 2]
 [1 2]]

[[3 6]
 [3 6]]


In [199]:
#5 Determinate
n1=np.matrix(range(11,20))
n2=n1.reshape(3,3)
print(n2)
print()
n3=np.linalg.det(n2)
print("Determinent:",n3)

[[11 12 13]
 [14 15 16]
 [17 18 19]]

Determinent: -2.131628207280298e-14
